---
- name: ChangeArgumentsJVMsWebSphereAS
  hosts: serverswas
  gather_facts: false
  tasks:
    - name: block selector for WAS
      block: 
        - name: Install and configure Zorka Agent
          include_role:
            name: zorka-install-was
    
        - name: Configure JVM arguments
          include_role:
            name: change-jvm-args
          vars:
            argsjvm_patwascmd: "/opt/IBM/WebSphere/AppServer/bin"
    
        - name: Restart JVMs
          shell: Add commads for JVM restart here
          register: reg_out
      when: jvm == 'WAS'

    - name: block for JBOSS tasks
      block:
        - name: Install and Configure JBOSS
          include_role:
            name: zorka-install-jboss
            
      when: jvm == 'JBOSS'