---
# tasks file for zorka-install-was
- name: Check previous installation
  include_tasks: pre_req.yml

- name: Get binary files
  include_tasks: file_transfer.yml

- name: Zorka Install
  include_tasks: install.yml

- name: Zorka Configure
  include_tasks: configure.yml
